replicaCount: 2

image:
  repository: hemanth0725/k8s-helm-sample
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  host: local.k8s
  path: /