name: CI/CD for Local Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm install -g snyk
      - run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - run: snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build-and-scan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/k8s-helm-sample:latest
          docker build -t $IMAGE .
          docker push $IMAGE

  deploy:
    runs-on: self-hosted
    needs: build-and-push-image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - run: |
          helm upgrade --install k8s-helm-sample ./helm \
            --set image.repository=${{ secrets.DOCKER_USERNAME }}/k8s-helm-sample \
            --set image.tag=latest
